targa changes for AOKP

diff --git a/releasetools/squisher b/releasetools/squisher
--- a/releasetools/squisher
+++ b/releasetools/squisher
@@ -35,10 +35,39 @@ if [ ! -f "$OTAPACKAGE" ]; then
 	exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/device/motorola/targa/releasetools/opticharger
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/aokp/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
+
+# Some products want a squashfs for xbin for space
+case "$TARGET_PRODUCT" in
+	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+	*) WANT_SQUASHFS=0 ;;
+esac
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+	fatal=0
+	MKSQUASHFS_VER_REQ=4
+	if type mksquashfs >/dev/null 2>&1; then
+		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+			echo
+			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+			fatal=1
+		fi
+	else
+		echo
+		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+		fatal=1
+	fi
+
+	if [ "$fatal" -ne 0 ]; then
+		echo
+		echo "       Unoptimized package is still available at"
+		echo "         $OTAPACKAGE"
+		exit $fatal
+	fi
+fi
 
 REPACK=$OUT/repack.d
 printf "Sanitizing environment..."
@@ -64,8 +93,7 @@ find ./ -name \*.apk | $XARGS $OPTICHARGER
 rm $REPACK/ota/system/app/FmRxApp.apk
 rm $REPACK/ota/system/app/FmService.apk
 rm $REPACK/ota/system/app/FmTxApp.apk
-rm $REPACK/ota/system/app/Music.apk
-rm $REPACK/ota/system/app/RomManager.apk
+#rm $REPACK/ota/system/app/RomManager.apk
 
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
@@ -117,15 +145,10 @@ rm -rf $REPACK/ota/recovery
 [ -d $REPACK/ota/system/lib/modules ] && \
 	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
-# Copy libvoicesearch as it's getting messed up in the build
-cp -f $ANDROID_BUILD_TOP/vendor/google/prebuilt/lib/libvoicesearch.so $REPACK/ota/system/lib/libvoicesearch.so
-mv $REPACK/ota/system/app/TargaProgramMenu.apk $REPACK/ota/system/app/ProgramMenu.apk
-mv $REPACK/ota/system/app/TargaProgramMenuSystem.apk $REPACK/ota/system/app/ProgramMenuSystem.apk
-
 # Determine what to name the new signed package
 REALDATE=`date +%F-%H_%M`
 
-OUTFILE=$OUT/902-ICS-4.0.3_r1-$TARGET_PRODUCT-$REALDATE.zip
+OUTFILE=$OUT/AOKP-4.0.3_r1-$TARGET_PRODUCT-$REALDATE.zip
 
 # Pack it up and sign
 printf "Zipping package..."
@@ -152,13 +175,5 @@ echo "Package complete: $OUTFILE"
 cat $img.md5sum
 echo
 )
-
-#if you want to run a custom upload script put it in ~/upload.sh
-if [ -f ~/upload902.sh ];
-then
-	echo "Running upload script"
-	upload=~/upload902.sh
-	. $upload
-fi
 
 exit 0
